apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iptables-watcher
  labels:
    app: iptables-watcher
spec:
  selector:
    matchLabels:
      app: iptables-watcher
  template:
    metadata:
      labels:
        app: iptables-watcher
    spec:
      hostNetwork: true
      serviceAccountName: iptables-watcher-sa  # Reference the service account
      containers:
        - name: iptables-container
          image: portforward:0.1  # Image with kubectl pre-installed
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                # Get the list of running pods created by the "iptables-watcher" deployment
                PODS=$(kubectl get pods --selector=run=my-nginx --field-selector=status.phase=Running -o name);
                if [ -n "$PODS" ]; then
                  echo "Detected new Nginx pod(s): $PODS";
                  /path/to/your-script.sh;  # Run the custom script when pod starts
                fi;
                sleep 10;  # Poll every 10 seconds
              done;
          volumeMounts:
            - name: script-volume
              mountPath: /path/to/your-script.sh
              subPath: your-script.sh
      volumes:
        - name: script-volume
          configMap:
            name: iptables-watcher-script-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iptables-watcher-script-config
data:
  your-script.sh: |
    #!/bin/sh
    echo "Running custom script because an Nginx pod has started..."
    # Add your script logic here
    # Example: Send notification, reconfigure services, etc.
